[package]
name = "ai-veto"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
common-rpc = { path = "../common-rpc" }
tokio.workspace = true
tonic.workspace = true
prost.workspace = true
prost-types.workspace = true
serde.workspace = true
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ollama-rs = "0.3.4"
serde_json.workspace = true
