[package]
name = "mock-veto"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
common-rpc = { path = "../common-rpc" }
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
clap.workspace = true
